### ISSUE TITLE
interactive session invoked when `file = ''` in `SS_readdat`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#589] opened 2021-12-20 02:53 UTC
## Problem

https://github.com/r4ss/r4ss/blob/155a52190f4a77e32d51d9f9d6806961c51de5ac/R/SS_readdat.R#L39

with `file = ''` as the input argument leads to the following R console output. Note that I also show the output from `scan(NULL)` and `scan("")` to show how I figured out what was going on.
![image](https://user-images.githubusercontent.com/4108564/146704401-bad7a719-ecc8-46ef-a4cd-7ccd7c7f118b.png)

I didn't have the `ss3roms` package loaded so the value returned by `file.path` was `''`. Then `scan(file = '')` led to the previous screen shot, which was an interactive session with R where it wanted me to type in a value for the file.

## Proposed solution

I think we should use `if (fs::file_exists()) {} else {}` where the else statement give users a warning that the file doesn't exist. We have too many downstream repositories that are based on simulations that could stall out with the interactive session to allow users to put in a value. I am open to other ideas though on how to fix this or maybe the way it is coded was intended?

**Comment by k-doering-NOAA** [comment] 2021-12-20 14:12
That makes sense to me, @kellijohnson-NOAA ! I don't think the interactive session was intended, but just an unintended side effect of using `scan()`. The fix sounds reasonable to me - thanks for figuring this out!

**Comment by k-doering-NOAA** [comment] 2022-06-16 12:12
I just looked at the main branch and this instance of scan() no longer exists. There were a few other instances, but the uses always appended a file extension, so I don't think it is possible to get `scan("")` by accident. Closing this out.

**Closed by k-doering-NOAA** 2022-06-16 12:12 UTC
Labels: enhancement, low priority
