### ISSUE TITLE
slow SS_writedat

### ISSUE THREAD

**Issue by GwladysLambert** [r4ss/r4ss#157] opened 2017-05-03 01:18 UTC
The printdf function in SS_writedat runs very slowly to copy across lengths and age comps on my computer. It seems to write them line by line which is a problem when using conditional age at lengths in simulations. 

I have replaced: 
printdf(datlist$lencomp)
with:
write.table(datlist$lencomp, file=outfile, append=T, col.names=F, row.names=F)

and did the same thing with the agecomp line:
from
printdf(datlist$agecomp)
to
write.table(datlist$agecomp, file=outfile, append=T, col.names=F, row.names=F)

And it runs significantly faster for me (i.e. for a simulation with only 50 rows of lengths and 1000 of CAAL, it wrote the file in 3'' instead of 2'43'')

I thought I should suggest this change or to look into it further?

**Comment by taylori** [comment] 2017-05-03 18:28
Good idea, @GwladysLambert. For the model I just tried with less than 1000 lines of age data, write.table increased the speed from 0.8 seconds to 0.15. For a bigger model and/or a simulation analysis where you're writing lots of files, I could see that the difference could add up.

The only drawback of write.table is that you don't get nicely formatted columns, which can be useful for finding problems in the input files. Therefore, I added faster=TRUE/FALSE switch in commit 20845496ec74018f87b492f80acabb3452b8c4f9 where faster=TRUE implements your suggestion and uses write.table.

Let me know if this doesn't work as expected. Example output in the two formats is shown below.
-Ian

**faster=FALSE:**
```
 #_Yr Seas FltSvy Gender Part Nsamp f16 f18 f20 f22 f24 f26 f28 f30 f32 f34 f36 f38 f40 f42 f44 f46 f48 f50 f52 f54 f56 f58 f60 f62 f64 f66 f68 f70 f72 f74 f76 f78 f80 f82 f84 f86 f88 m16 m18 m20 m22 m24 m26 m28 m30 m32 m34 m36 m38 m40 m42 m44 m46 m48 m50 m52 m54 m56 m58 m60 m62 m64 m66 m68 m70 m72 m74 m76 m78 m80 m82 m84 m86 m88
 1993    1      1      0    0  36.6   0   0   0   0   1   1   1   0   1   1   4   5   4   4   2   0   1   1   2   0   1   1   0   1   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 1994    1      1      0    0  45.4   0   0   0   0   0   2   3   2   4   9   7   4   3   9   8   2   2   2   0   2   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
 1995    1      1      0    0  46.5   0   0   1   0   0   1   1   7   4   3   3   5   9   2   3   2   0   1   1   2   0   0   0   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
```

**faster=TRUE:**
```
#_Yr Seas FltSvy Gender Part Ageerr Lbin_lo Lbin_hi Nsamp f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32 f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50 f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14 m15 m16 m17 m18 m19 m20 m21 m22 m23 m24 m25 m26 m27 m28 m29 m30 m31 m32 m33 m34 m35 m36 m37 m38 m39 m40 m41 m42 m43 m44 m45 m46 m47 m48 m49 m50 m51 m52 m53 m54 m55 m56 m57 m58 m59 m60 m61 m62 m63 m64 m65
1983 1 1 1 0 1 10 10 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1996 1 1 1 0 1 21 21 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
1983 1 -1 3 0 1 1 37 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by GwladysLambert** [comment] 2017-05-03 18:37
Yes that is the draw back with the write.table option but it works fine for reading the data file and running the models and really does speed up the simulations (e.g. in ss3sim). Thanks @taylori

**Comment by yukio-takeuchi** [comment] 2017-05-03 21:49
Probably you already realized printdf is a wrapper function internally calling print.data.frame function.
I could not remember the reason why printdf is used instead of print function. I remember that I tested several functions including write.table function as you can find the source code of prinydf. I suspect, this is related to the case if direct modification of conditional length at age or any other data in the form of data.frame stored as element in list "datlist" by using function in dplyr or data.table. If they are done ,  since SS_writedat uses sink function to redirect output to a file instead of screen, print produced truncated output instead of whole data.table (data.frame is automatically converted to data.table if functions in dplyr or data.table are used). 
As for the change made in commit 2084549, I have a slight concern of mixed use of output using "sink" and explicit output using file argument in write.table to the same file. I guess, this may cause unexpected results.  Probably it would be better to rewrite SS_writedat to avoid sink as has been done in SS_writectl. For the time being, I would like to propose to change printdf function to 

`  printdf <- function(dataframe){
    # function to print data frame with hash mark before first column name
    names(dataframe)[1] <- paste("#_",names(dataframe)[1],sep="")
    if(faster){
 #     writeLines(paste0("#_", paste(names(datframe), collapse=" ")))
      write.table(dataframe, append=TRUE, col.names=TRUE, row.names=FALSE)
    }else{
       print.data.frame(dataframe, row.names=FALSE, strip.white=TRUE)
   }
  }
`

Since printdf is used several places in SS_writedat, this change should make SS_writedat prety faster, though I have not tested.

**Comment by taylori** [comment] 2017-05-04 04:52
Thanks for the idea, @yukio-takeuchi. I made the change you suggested (also adding "quote=FALSE") in commit bb4ed69. This only improved the speed by about 10% for the model I was using because the other tables are all smaller than the length and age compositions. There will be a bigger benefit to models with generalized size comp data, which weren't included in the previous commit.

I have no problem with moving away from sink as you've done in SS_writectl_3.24, but don't have time to make that change now. If anyone sees any unexpected behavior in this function, please let me know.

Also note that SS_writedat doesn't yet work with SS version 3.30.

**Comment by taylori** [comment] 2017-05-05 18:46
@yukio-takeuchi has kindly re-written the SS_writedat function to remove `sink()` (see commit 9662cae). This should result in more stable behavior. The `faster` option is still available and the revised function seems to work well with and without that turned on.

Note that when using `faster=TRUE`, you will get some warnings like
```
1: In write.table(dataframe, file = zz, append = TRUE, col.names = TRUE,  :
  appending column names to file
```
which is just R's way of telling you that it is adding a header row somewhere in a file that is not the top (which typically would be something to avoid, but in this case, the file contains multiple tables, each of which has a header).

Thanks again, @yukio-takeuchi. I will now close this issue and open another noting the need to work on a version of SS_writedat for 3.30 at some point in the future (doesn't seem to be needed by anyone in the short term).

**Closed by taylori** 2017-05-05 18:46 UTC
