### ISSUE TITLE
Possible data grabbing issue with r4ss

### ISSUE THREAD

**Issue by latreesedenson-NOAA** [r4ss/r4ss#709] opened 2022-07-12 16:43 UTC
Hi,

@matthew-smith-noaa and I have updated our model from 3.24j to 3.30.19, but using the current version of r4ss 1.44.00 we run into an issue with plotting.
 
The following code, produces the error below:
```{r}
SS_plots(replist = base, uncertainty=F, sprtarg=0.30, btarg=0.3, datplot=T, minbthresh=-1,png=T, plot=c(1:24),
		 dir="default", pdf=F,printfolder="R_Plots_Report")
```
"Finished defining objects
Plots will be written to PNG files in the directory:
...
Starting biology plots (group 1)
Error in plot.window(...) : need finite 'ylim' values"

When you dig into this the bio6 plot is an issue as well as the bio8 plot. Below is what the bio6 plot looks like, bio8 should show fecundity but it is blank, and no other plots produced after this.
![bio6_maturity](https://user-images.githubusercontent.com/70522445/178545878-2786b5b7-1bc9-4d82-8abd-05d4a4c96ccc.png)
.

Not sure but this could be an r4ss flexibility issue with r4ss grabbing the wrong information given our model setup. Or we could have broken something in the transition, either way help would be greatly appreciated.

Thanks,
LaTreese & Matt

**Comment by iantaylor-NOAA** [comment] 2022-07-12 17:21
Hi LaTreese & Matt,
If the model ran with 3.30.19, then I don't think the problem is with your transition. It should work with r4ss but doesn't. I would guess it's because your model includes settings that we haven't tested in a while. 
Can you email me your model input files so I can try to debug this?
-Ian

**Comment by iantaylor-NOAA** [comment] 2022-07-12 18:29
Hi LaTreese & Matt,
Thanks for reporting this. 
For future reference, more details on the cause are here: https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/348.

I'll use this r4ss issue to post the steps that can be taken to deal with it outside of Stock Synthesis:
1. A quick fix to get the plots working for this model is to change from
`3 #_fecundity option:(1)eggs=Wt*(a+b*Wt);(2)eggs=a*L^b;(3)eggs=a*Wt^b; (4)eggs=a+b*L; (5)eggs=a+b*W`
to
`1 #_fecundity option:(1)eggs=Wt*(a+b*Wt);(2)eggs=a*L^b;(3)eggs=a*Wt^b; (4)eggs=a+b*L; (5)eggs=a+b*W`
which will cause the placeholder 999 values for the a and b parameters to calculate fecundity as 999 + 999 * Wt instead of 999 * Wt ^ 999 and avoid the "Inf" values in the Report file.

2. r4ss should skip the plots of maturity and fecundity as a function of length or weight when age-based vectors are supplied for maturity or fecundity as in this model.

3. Stock Synthesis could stop calculating fecundity-at-length from those parameters for models where a vector of age-based values is provided (subject of the issue linked above).

**Comment by iantaylor-NOAA** [comment] 2022-08-23 23:46
This issue has been resolved via changes to SS3 (https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/348) and r4ss commit 479a3cd9539ea4be40e660ffa955958844a03e1a. 
Older models that run into this can hopefully use the options listed in the comment above: https://github.com/r4ss/r4ss/issues/709#issuecomment-1182209655 to work around the problem.

**Closed by iantaylor-NOAA** 2022-08-23 23:46 UTC
Labels: bug, plots, quick fix
