### ISSUE TITLE
Print informative SS_plots output to HTML home page

### ISSUE THREAD

**Issue by colemonnahan** [r4ss/r4ss#79] opened 2015-11-11 04:09 UTC
Ian Stewart had the good idea to save the console output created by `SS_plots` and also include it on the HTML home page. A lot of this output is only useful for debugging, but some of it, such as the Francis weights output, bias adjustment values, and warnings. Since some of this text is in subfunctions (e.g., `SSplotBiology`) it would require changing quite a bit of the code, at least small bits across many files. I thought it'd be worth a discussion about how to approach this (or if we should) before I dove in and started tinkering around too much.

My first thought is to define a new `cat` function that serves two purposes: (1) prints to screen as before and (2) saves what is being printed to an object.

Something like this:

```
cat2 <- function(..., file){
    cat(...)
    c(file, ...)
}
file <- NULL
file <- cat2('test1\n', 'test2\n', file=file)
file <- cat2('test3\n and testing again\n', file=file)
file <- cat2(1:4, file=file)
file
cat(file)
```

I guess we'd either have to use a global variable or pass `file` along (not a good solution). @taylori and @allanhicks do you have any ideas/thoughts about this approach?

**Comment by taylori** [comment] 2015-11-11 05:04
This is a good idea and I like the cat2 concept.

It might be efficient to tackle #76 in conjunction with this issue as that issue was focused on the same concept of storing console output (from SS_output instead SS_plots) for inclusion in the HTML view. cat2 could either become a stand-alone r4ss function used by both functions or redefined within both functions.

Note that SS_fitbiasramp already produces an extended caption that looks something like:

> Points are transformed variances. Red line shows current settings forfor bias adjustment specified in control file.Blue line shows least squares estimate of alternative bias adjustmentrelationship for recruitment deviations (which may or may not be animprovement. For more information, see
>
> Methot, R.D. and Taylor, I.G., 2011. Adjusting for bias due to variability of estimated recruitments in fishery assessment models. Can. J. Fish. Aquat. Sci., 68:1744-1760.
>
> Estimated alternative inputs to SS control file associated with blue line in figure:

    1862.9   #_last_early_yr_nobias_adj_in_MPD 
    2010.0   #_first_yr_fullbias_adj_in_MPD 
    2010.0   #_last_yr_fullbias_adj_in_MPD 
    2010.1   #_first_recent_yr_nobias_adj_in_MPD 
    0.5012   #_max_bias_adj_in_MPD (1.0 to mimic pre-2009 models)   

This approach may work well better than the cat2 writing to file in some cases but surely not all.
-Ian

**Comment by taylori** [comment] 2015-11-11 05:06
Direct link to line 320 of SS_fitbiasramp for extended caption example: https://github.com/r4ss/r4ss/blob/master/R/SS_fitbiasramp.R#L320

**Comment by kellijohnson** [comment] 2015-11-11 14:46
For someone that uses `knitr`, `cat` is a nightmare when things are printed to the screen.
Yihu Xie suggests the following (http://yihui.name/knitr/demo/output/)
Many people like to use `cat()` to write messages in R, and this is a very bad practice, because it is inconvenient to turn off such messages. When we really mean messages, we should use `message()`. When you are unable to turn off some messages by `message=FALSE` in `knitr`, it is probably time to request the package authors to make some changes.

Just my 2 cents and one more thing to consider.

**Comment by taylori** [comment] 2015-11-12 16:49
I didn't know about message().

Not sure how much @colemonnahan wants to tackle but the "verbose"
switches on the cat statements are surely inconsistent and could be
replaced by message if we learn how to use it properly.

**Comment by colemonnahan** [comment] 2015-11-12 17:13
I've always used `message` as well but more out of habit than preference over `cat`. Each seems to have slight advantages. I'm not big on knitr to be honest, so I don't think any big changes to accommodate it are high priority (why not just run a script and use LaTeX?). How many people are using it?

This issue is something Ian Stewart has for me as a lower priority so maybe I'll get to it in a few weeks.

The tricky part is that the messages are spread through the subfunctions but also in `SS_plots`. So if we do something like I proposed above, and use a global variable, it'll get messy keeping track of that when people are running subfunctions separately and repeatedly.  I guess we could just ignore that global variable except in the `SS_html` function, initiating it as NULL at the top of `SS_plots`. Still, I think the bookkeeping would be kind of annoying. I'll keep thinking of alternatives.

**Comment by allanhicks** [comment] 2015-11-12 22:55
I see this a little bit differently. I don't see these purely as messages, but as output. My thought would be to write all of this output to a file. If individual functions write this, they can append to the file, resulting in a file with all of the output and the user can peruse it, or it can be parsed into the html file, etc.  Is the output to the console necessary?  It typically flashes by, is difficult to find what you are looking for and is available in the R object anyways.

Alternatively, we could start brand new and design a text document with output that is formatted in a particular way.  It is a hard decision of keeping on the path, or finding a new one.

Thanks for keeping me involved in this.

**Comment by colemonnahan** [comment] 2015-11-12 23:11
@allanhicks I think we should be careful to make the distinction between the types of things printed to the console. I agree that some are "messages" and some are "output." Some of them messages are informative only if there's an error ('starting plot #5') while others are important warnings/errors generated by the functions. Then there's the printed R objects. 

I believe Ian S. was suggesting we only pipe the warnings/errors and R object output (that's not already on another tab like Ian T. mentioned above w/ Francis weights). The warnings/errors tell the user to be cautious of interpreting the plots and to investigate the issues. 

So this means we wouldn't replace all of the `cat` statements with `cat2` but only a select few. There's not need to pipe most of the messages into the HTML file as far as I can see.

I'm curious by your idea of a new text document. What did you have in mind exactly?

**Comment by allanhicks** [comment] 2015-11-12 23:21
Hmmm. I may be misinterpreting your task.  Ian S. and I have been talking
about putting the output from SS_output into the home page of the html
file.  The output from SS_plots is simply what plot number is plotted or
skipped.  Is that useful or not is the question? I find that the plot
numbers and what they refer to are useful, but that is something I use
later and may better be locatd in the help file.

I feel that including the output from the SS_output in the html home page
would be very useful. If you remember at CAPAM, I had to pre-make
everything, and when I went to show the table of tuning for length comps, I
didn't have it because it is output to the R console and lost once that
window is closed.  I feel that a text file with that information would be
welcomed in with the plots for a specific run, or in that same folder as
the run.  Then, there would be a record of what we feel is important to the
person interpreting the run.

Furthermore, if a text file is written, it will persist there, but could
also be parsed into the html file as well as the pdf file and possible made
as a graphic to display when displaying plots within R.  I think that you
can see I'm leaning towards rethinking this output, but given that it is
low priority, it may be useful to try to pipe whatever output is already
created by SS_output into text file.

I may be on a different topic, at which point, feel free to make a new
issue.

Thanks for your work on this.

**Comment by colemonnahan** [comment] 2015-11-13 16:28
@allanhicks I agree that the ``SS_output` info is useful. But I also would argue that some of the messages that are produced by `SS_plots` and subfunctions are as well. For instance if using wtatage, it prints a warning that the biology plots won't necessarily be meaningful. That seems like a good tidbit to add to the HTML, in fact thinking out loud here, probably each set of warnings from subfunctions should go on their respective pages. So the `SSplotBiology` messages go on the biology tab, etc.

It's certainly not an easy task. I'm happy to help where I can, but will defer to the more experienced developers about the best approach for the long-term goals of the package. Piping to a separate file seems very reasonable to me.

**Comment by kellijohnson** [comment] 2015-11-13 17:00
More thinking outloud: could not we use the `verbose` argument and change it from only accepting 'TRUE' or 'FALSE' to also accepting a numeric level that dictates what information is printed. Each statement whether produced by 'cat', 'cat2', 'message', 'warning', or 'stop' could then be placed in an ordered category. Then users could specify a vector of categories or single category. This may be more complicated than necessary.

Also @colemonnahan I think that knitr is probably the only way to get assessment authors that use word to move towards something more streamlined and tex is probably out as far as a global change. So if we can make things more compatible with knitr without breaking them I see its actual use more likely.

@taylori let me know if there is a task you would like me tackle regarding this, but like @colemonnahan I am inclined to defer to the more experienced.

**Comment by sandeeplshetty** [comment] 2015-11-16 10:09
how to print plots that are generated in the results...

**Comment by taylori** [comment] 2015-11-20 15:37
@sandeeplshetty I'm not sure I understand your question. The R function we're discussing prints the plots to PNG files by default that can be viewed individually or in groups through the automatically created HTML files.

@colemonnahan @kellijohnson @allanhicks my suggestion is to not get bogged down by the idea of a wholesale change in everything that gets printed but instead to identify small steps that can be more easily taken by a diverse group all of whom have with other things to do.

Perhaps a new page on the wiki would be useful for describing this plan, but I'm thinking along the lines of the following:

### warnings
warnings like the one in SSplotBiology for models with empirical weight-at-age saying that growth plots probably don't make sense should be included in the caption for those plots using something like

    if(wtatage_switch){
      caption <- paste(caption, wtatage_warning)
    }
We could also have those plots skipped but then it would be good to add something to the HTML (perhaps a empty plot with caption) noting why they aren't present. A generic warning at the top of the function was a lazy shortcut that I took.

### debugging notes
statements about which plots have been produced are useful for debugging functions that crash but if the function crashes, you don't get the HTML so while it might be worthwhile to write this to a file, there's probably no use in saving it in a format suited for HTML viewing.

### informative info
useful output from things like the recruitment bias adjustment and Francis tuning functions are already available in the figure captions but could perhaps be written to a text file or some more easily accessible format as well.

**Comment by taylori** [comment] 2016-03-03 19:06
Hi @colemonnahan @kellijohnson @allanhicks,
Do you have any interest in further discussion of revisions to the methods of outputting warnings and messages in r4ss? I'm getting back into development mode to start working through the long list of issues, so it would be useful to at least make new code conform to an improved warning/message system if we can come up with one.

**Comment by colemonnahan** [comment] 2016-03-03 22:35
@taylori I haven't thought much about this since last year. 

It seems to me the first step is to to formalize what you have above: coming up with an ordered hierarchy of types of messages. 

Then, come up with a list of all the ways in which functions are used (and will be in the future), and how that interacts with your message hierarchy. 

Will the shift to SS4 make any huge difference here? One thought would be to include these changes when that version of r4ss is rolled out.

**Comment by taylori** [comment] 2016-03-03 23:35
I copied text from this issue into a new wiki page that can be used to refine the plan for outputting messages and warnings: https://github.com/r4ss/r4ss/wiki/ideas-for-messages-and-warnings

Regarding future releases of SS, version 3.3, which I expect will be formally released later in 2016, is expected to have only minor impact on r4ss (indeed, current r4ss is already compatible with some development versions of SSv3.3). It is not yet clear to me what shape a next generation (SS4?) model will take and I don't see any timeline of work toward the development of such a model, so it's not worth worrying about that step at this stage.

**Comment by kellijohnson** [comment] 2016-03-07 23:06
I think the best way forward would be to start with the bugs (e.g., not being able to turn off output if you want to) and adding warnings that are printed to the screen to the plots themselves as @colemonnahan has suggested. Then after that is done then maybe we can work at what sort of additional output is helpful.

**Comment by k-doering-NOAA** [comment] 2022-06-14 20:59
To me, this seems like a duplicate of #76. I think we can close out one of these.

**Comment by iantaylor-NOAA** [comment] 2022-06-14 22:29
Thanks to this issue, `message()` is now used in 60 places in the r4ss code and @k-doering-NOAA has done lots of recent clean up on the messages such as in recent PR #680. Any remaining work can be covered by issue #76 and #660.

**Closed by iantaylor-NOAA** 2022-06-14 22:29 UTC
Labels: duplicate
