### ISSUE TITLE
SSplotRecDist does not work properly

### ISSUE THREAD

**Issue by yukio-takeuchi** [r4ss/r4ss#467] opened 2021-01-18 12:26 UTC
It seems that the format of data.frame contained in recdist changed at some point.

When recmat is calculated following change was needed to work with Report.sso from SS3.30.16

Original
```r
 recmat[iarea, iseas] <- sum(recdist[["Value"]][recdist[["Area"]] == iarea & recdist[["Seas"]] == iseas & recdist[["Used"]] == 1])
```
Modified
```r        
recmat[iarea, iseas] <- sum(recdist[["Frac/sex"]][recdist[["Area"]] == iarea & recdist[["Seas"]] == iseas])
```

**Comment by kellijohnson-NOAA** [comment] 2021-01-18 13:00
@yukio-takeuchi thank you for noticing this, letting us know, and also for proposing a fix. It is a federal holiday today in the US, so Ian will not be able to get this fixed today. Is this something you need immediately in the development branch or will later this week be sufficient?

**Comment by yukio-takeuchi** [comment] 2021-01-18 13:17
Hi,

In my model replacing original line in SSplotRecDist to calculate remat to the modified code in the previous post resolved the problem. So it is not necessary to update development branch immediately.

It may be helpful that if Ian or someone can check when format of receipt data.frame change and insert some code to make this function compatible to both old and current format.

Yukio

**Comment by yukio-takeuchi** [comment] 2021-01-19 21:59
WOOPS,
Together with  #468, I  accidentally  push local change for fix to development branch instead of my folk. Can I request to switch from this commit  back to previous one so that I will make PR from my folk again.

**Comment by iantaylor-NOAA** [comment] 2021-01-19 22:45
@yukio-takeuchi, I think the changes you accidentally pushed to the development branch look good so it's not worth reverting that commit and going through the pull request process.

I've been meaning to limit who can write directly to the r4ss repository which will make it easier to have contributions go into forks and get merged via Pull Requests.  (I just pushed to the wrong fork of a repository last week so I know how easy that is).

@kellijohnson-NOAA thanks for the thorough review of uses of `recruitment_dist`. In most other places I think it makes sense to convert the output associated with 3.24 models to the 3.30 format, but I'm not sure it's worth the effort in this case as it's not just changes in column names (which indeed appears to have been associated with the change to 3.30), but a also shift from 1 table to 3 tables which are now represented as a list, which first appeared in 3.24Q. I'm not sure what the "Used?" column was intended for in 3.24 models, but that column is indeed gone in 3.30 so it doesn't seem worth spending lots of time tracking this down. Thus, the 

I just removed the extraneous line in `SSplotNumbers()` in commit f051069b115d4286da1c272f34231c39220e0e17. 

I'm not seeing the issue with `SSplotTimeseries()` because I believe the tests on this line should be satisfied by 3.30 models https://github.com/r4ss/r4ss/blob/ccc448b0e7f6ab55af074b7b1e0b060dafa61efe/R/SSplotTimeseries.R#L274-L275 and earlier models didn't have the possibility of settlement after the year of spawning so that adjustment isn't needed.

**Closed** 2021-01-20 05:28 UTC
Labels: bug, plots
