### ISSUE TITLE
Units in Executive Summary captions and column headers

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r4ss/r4ss#549] opened 2021-08-12 22:17 UTC
https://github.com/r4ss/r4ss/blob/64b9e62aa80d87d68107a602f9bb08bd3d5bf0f5/R/SSexecutivesummary.r#L1190

I am not going to worry about it at the moment for lingcod, but it would be good in the future to look up the units and add these to the caption and / or the column headers. For example, catches are in mt and recruits are in 1000s of fish for most models.

**Comment by iantaylor-NOAA** [comment] 2021-12-03 18:41
Duplicate of #559 (keeping that one as it includes a response).

**Closed by iantaylor-NOAA** 2021-12-03 18:41 UTC
Labels: duplicate
