### ISSUE TITLE
[Bug]: check_exe() doesn't recognize executable not named "ss"

### ISSUE THREAD

**Issue by N-DucharmeBarth-NOAA** [r4ss/r4ss#741] opened 2022-08-23 21:28 UTC
### Describe the bug

`check_exe()` does not recognize executable specified using the `exe` argument when used within the `retro()` function.

### To Reproduce

1. In a linux environment navigate to a directory with SS files and an SS3 executable (e.g. `cd path/to_my_dir/`) 
2. The SS3 executable can not be named "ss" in order to recreate the error. In my case it was named "ss_linux".
3. Run the following code `retro(dir=getwd(),exe="ss_linux",verbose=TRUE)`

### Expected behavior

I expected the `retro(dir=getwd(),exe="ss_linux",verbose=TRUE)` function to run.

### Screenshots

![Capture](https://user-images.githubusercontent.com/97110196/186268199-4423b8d3-b77b-4e44-8afb-07b896b04a07.PNG)

### Which OS are you seeing the problem on?

Linux

### Which versions of r4ss and SS3 are you seeing the problem on?

v1.46.1 of r4ss and 3.30.16.00 of SS3

### Additional Context

The following function call `retro(dir=getwd(),exe="ss_linux",verbose=TRUE)` appears to fail at[ line 107 ](https://github.com/r4ss/r4ss/blob/main/R/retro.R) of the code.

It is able to create the first directory `retrospectives/retro0/` and paste the 4 SS3 files and the "ss_linux" executable. This indicates that the function is indeed seeing `exe="ss_linux"`. However, when `check_exe()` is called on line 107, it appears to be looking for "ss" and naturally doesn't find it (see uploaded error screenshot). This indicates to me that the default value for `exe="ss"` in `check_exe()` is not being overwritten by the `exe` value from `retro()`.

If I make a copy of "ss_linux" and save it as "ss" and run `retro(dir=getwd(),exe="ss")` then everything runs as it should.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment] 2022-08-23 23:27
Thank you @N-DucharmeBarth-NOAA for testing the latest code and reporting this bug.
I was able to replicate the error and tracked it down to failing to pass the exe argument to the `run()` function which calls `check_exe()`, now corrected in 77be304.

Let me know if it now works for your workflow.


FYI, after the fix I'm now getting a different error on linux if I use the "\~" in the exe location (it works if I use "/home/itaylor" instead of "~" in the path to the exe).
```
r4ss::retro(exe = "~/h_itaylor/SS/SSv3.30.19.01_Apr15/ss_linux", verbose = TRUE)
Executable found in PATH at /home/itaylor/h_itaylor/SS/SSv3.30.19.01_Apr15/ss_linux
Running retrospective in /more_home/h_itaylor/github/r4ss/inst/extdata/simple_small/retrospectives/retro0
copying files from
 /more_home/h_itaylor/github/r4ss/inst/extdata/simple_small/
to
 /more_home/h_itaylor/github/r4ss/inst/extdata/simple_small/retrospectives/retro0
Unix binaries are: variance
copying complete
Executable found in PATH at /home/itaylor/h_itaylor/SS/SSv3.30.19.01_Apr15/ss_linux
Changing working directory to /more_home/h_itaylor/github/r4ss/inst/extdata/simple_small/retrospectives/retro0 and running model using the command: ~/h_itaylor/SS/SSv3.30.19.01_Apr15/ss_linux
Input 'show_in_console' = FALSE, so writing console output to console.output.txt
Error in system2(command = command, args = extras, stdout = ifelse(show_in_console,  :
  error in running command
```
Digging deeper, it appears that the `system2()` function fails while `system()` succeeds.

I'll work on researching the differences between those functions to try to figure out the cause, but if you have any ideas, please let me know. Also, please report if you either get this same error or not.
```
> command
[1] "~/h_itaylor/SS/SSv3.30.19.01_Apr15/ss_linux"
> system2(command = command)
sh: ~/h_itaylor/SS/SSv3.30.19.01_Apr15/ss_linux: No such file or directory
Warning message:
In system2(command = command) : error in running command
> system(command = command)
 reading from starter.ss
 reading from data file
...
```

@yukio-takeuchi, do you see anything obvious that I'm doing wrong here?

**Comment by N-DucharmeBarth-NOAA** [comment] 2022-08-24 03:05
Hi @iantaylor-NOAA ,
Thanks for looking into this so quickly! Your fix corrected the issue that I was having. I don't have my executable in the path and am not referencing it with a "~" so am not seeing the different error that you mentioned.

As an aside, if I put the executable in the path does that avoid copying it into each retrospective sub-directory? From a disk management standpoint I'd like to cut down on copying redundant files if possible.

**Comment by roliveros-ramos** [comment] 2022-08-24 12:49
Hi @iantaylor-NOAA, I think

`exe = path.expand(exe)`

might fix the problem. The issue could be a quoting problem (shell dependent) avoiding proper tilde expansion.

**Comment by iantaylor-NOAA** [comment] 2022-08-24 18:32
@roliveros-ramos, thank you for the `path.expand()` suggestion. That fixed it.

@N-DucharmeBarth-NOAA, I made a few further changes to `check_exe()` in https://github.com/r4ss/r4ss/commit/77c1afbdeb7427f6c6f28c3b4d9270d968cf0f9d to include `path.expand()` and also sort out when "./" gets added on linux and mac systems. Please let me know if anything doesn't work right for you.

Also, with regard to copying the executable, the current implementation of `retro()` will copy the executable to each sub-directory if it is found in the initial source directory, `dir`. However, if it is not found there, and your "exe" input includes adequate path info to find it, or if it's in the user's PATH, then the function should work fine and not copy any exe files.  However, I think now that a better approach would be to not copy the exe even if it's in the source directory and instead just use that same exe with each sub-directory.

**Comment by N-DucharmeBarth-NOAA** [comment] 2022-08-26 00:52
@iantaylor-NOAA Ok, I will let you know if the changes to `check_exe()` from https://github.com/r4ss/r4ss/commit/77c1afbdeb7427f6c6f28c3b4d9270d968cf0f9d cause any issues on my side. However, before I update to the latest version for testing, would you be able to add 'exe' as an argument to `run()` called from within `profile()` ([line 460](https://github.com/r4ss/r4ss/blob/main/R/profile.R))? That function is going to have the same issue as `retro()` originally did. This way I can test both functions at the same time. Thanks!

I checked `jitter()` and it looks like 'exe' is listed as an argument for `run()` so that function should be ok. I'm not sure if there would be any other places where 'exe' needs to be added as an argument to `run()` though.

**Comment by iantaylor-NOAA** [comment] 2022-08-26 15:40
Hi @N-DucharmeBarth-NOAA, sorry for the oversight--thanks for checking `profile()`. There are just 4 functions that use `run()` (which prior to the changes in https://github.com/r4ss/r4ss/pull/722 all had their own inconsistent and poorly implemented calls to `shell()` or `system()`): `retro()`, `profile()`, `jitter()`, and `tune_comps()`. And it looks like this issue has now been resolved in all of them thanks to your help.

I'll leave this issue open until you've had a chance to install the updated r4ss and report back on whether it works with an executable not named "ss" on your linux system.

**Comment by N-DucharmeBarth-NOAA** [comment] 2022-08-31 22:23
Hi @iantaylor-NOAA, I was able to test this morning with the updated version and everything looks like it is running fine. You may close this issue.

On another note, I've noticed that `profile()` is hard-coded to only read the first 11 components of the LIKELIHOOD section in Report.sso (lines 465-473). Given that the number of components in this section of the report may be different from model to model, it might be good to make this dynamic. I'll open up a new issue with a code suggestion once I've had more time to think it over.

**Comment by iantaylor-NOAA** [comment] 2022-08-31 23:05
Thanks for testing and following up, @N-DucharmeBarth-NOAA.

Please do open a new issue. I forgot that the profile() function even reads the table of likelihoods because my habit is always to read the full model output from all the models as in the example here: https://github.com/r4ss/r4ss/blob/main/R/profile.R#L114-L117. 
I think the hardwired 11 lines has been in place since the beginning of that function over a decade ago. One quick solution that surely would run just as fast as avoid duplicating code would be to replace that table-reading section in profile() with a call to [SS_read_summary()](https://github.com/r4ss/r4ss/blob/main/R/SS_read_summary.R) and then use the likelihood table it returns.

**Closed by iantaylor-NOAA** 2022-08-31 23:05 UTC
Labels: bug
