### ISSUE TITLE
[Bug]:  Profiling over multiple parameters doesn't work

### ISSUE THREAD

**Issue by Ovec8hkin** [r4ss/r4ss#810] opened 2023-05-04 04:04 UTC
### Describe the bug

When following the vignette instructions for profiling over multiple parameters simultaneously using `r4ss::profile`, the example code does not actually run for all parameter combinations, it only runs for the first combination of parameters.

### To Reproduce

Run the example vignette at `?r4ss::profile`. It should run 25 models, but instead runs 1.

### Expected behavior

The profile function is expected to run across combinations of parameters. It works fine for a single parameter, just not for multiple. 

### Which OS are you seeing the problem on?

Mac

### Additional Context

I assume this is an relative uncommon use case of `profile` which is how this has slipped through. The fix is simple (I implemented for use with the SSPT 2023 assessment which needed it to profile over mortality). I can submit a PR for it.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/r4ss/r4ss#code-of-conduct)

**Comment by iantaylor-NOAA** [comment] 2023-05-04 17:35
Hi @Ovec8hkin,
Sorry for the issue. The example under https://r4ss.github.io/r4ss/reference/profile.html#ref-examples isn't great because it depends on having a model with the low-fecundity stock-recruit relationship. I just run the following more reproducible code below and it ran all 9 models in a 3x3 grid. Could you share more about the issue you had or whether swapping out the example with what's below would be an adequate fix?

```
# alternative 2D profile that's more easily reproducible
# (assumes you have an SS3 exe in your PATH, change name as needed)

dir_simple_small <- file.path(
  path.package("r4ss"),
  file.path("extdata", "simple_small")
)

# create temporary directory and copy files into it
dir_prof <- file.path(tempdir(), "profile_2D")
copy_SS_inputs(
  dir.old = dir_simple_small,
  dir.new = dir_prof,
  create.dir = TRUE,
  overwrite = TRUE,
  copy_par = TRUE,
  verbose = TRUE
)


# create table of M values for females and males
par_table <- expand.grid(
  M1vec = c(0.05, 0.10, 0.15),
  M2vec = c(0.05, 0.10, 0.15)
)

# run model once to create control.ss_new with
# good starting parameter values
# exe is assumed to be in PATH, add "exe" argument if needed
run(dir_prof, extras = "-nohess")

# run profile using ss_new file as parameter source and
# overwriting original control file with new values
prof.table <- profile(
  dir = dir_prof,
  oldctlfile = "control.ss_new",
  newctlfile = "control.ss",
  string = c("NatM_uniform_Fem_GP_1", "NatM_uniform_Mal_GP_1"),
  profilevec = par_table,
  extras = "-nohess"
)

# get model output
profilemodels <- SSgetoutput(
  dirvec = dir_prof,
  keyvec = 1:nrow(par_table), getcovar = FALSE
)
n <- length(profilemodels)
profilesummary <- SSsummarize(profilemodels)

# add total likelihood (row 1) to table created above
par_table$like <- as.numeric(profilesummary$likelihoods[1, 1:n])

# reshape data frame into a matrix for use with contour
like_matrix <- reshape2::acast(
  data = par_table,
  formula = M1vec ~ M2vec,
  value.var = "like"
)

# look at change relative to the minimum 
# (shows small change when female and male M are equal, 
# big change when they are different)
like_matrix - min(like_matrix)
#         0.05    0.1    0.15
# 0.05   6.938 32.710 121.959
# 0.1   49.706  0.000  27.678
# 0.15 154.897 44.768   5.366
```

**Comment by Ovec8hkin** [comment] 2023-05-04 20:37
@iantaylor-NOAA Ill try your updated version later today. I was running into a problem where `profile` would only run a single model even though several sets of model parameters were provided in, presumably, the correct format.

**Comment by iantaylor-NOAA** [comment] 2023-10-13 21:56
Example in help page for `profile` was improved and no further issues have been reported, so closing this issue.

**Closed by iantaylor-NOAA** 2023-10-13 21:56 UTC
Labels: bug
